### PR TITLE
1.0.2

### PR DESCRIPTION
**Pull request by menor**

### CODE REVIEW

**Comment by menor** [comment]
Don't merge this for now @nsb I just saw there's another PR from @heinburger pending

**Comment by heinburger** [comment]
I would suggest that we move to 1.1.0 since we have quite a few new components and changes. Also this was branched off of the beta.8, and we are on beta.14 (which is not yet in master) - what do you think?

**Comment by menor** [comment]
I don't know, at least put beta 14 on master I think and then proceed from there,

**Comment by menor** [comment]
Can you and @nsb resolve this PR? https://github.com/resmio/mantecao/pull/96
Then I guess we update the version

**Pull request closed without merging**
