### PR TITLE
Component fixes, fixes #93

### LINKED ISSUE #93: Fix TextField component
When using it in the resmio app, in the new customer edit section, we get this warning:
image

DateSelector is also there and gives no warning so maybe we can take a look at that one to fix this one.

### PR DESCRIPTION
**Pull request by heinburger**

### CODE REVIEW

**Comment by nsb** [comment]
Should build bundle.js be in there?

**Comment by heinburger** [comment]
yes - this is the bundle for the styleguide that is hosted under the `docs/`

**Comment by nsb** [comment]
@heinburger I approved but the PR has merge conflicts.

**Comment by heinburger** [comment]
@nsb - I fixed the merge conflicts

**Pull request merged**
