### PR TITLE
Add rollico to the storybook template

### PR DESCRIPTION
**Pull request by menor**
That way we have the base but we don't bundle it

### CODE REVIEW

**Comment by heinburger** [comment]
not sure why there are 2 code coverage reports for this - do you know why there are 2 checks? Will this be merged now?

**Comment by menor** [comment]
I only see one codecov sorry, where's the other one?

**Comment by heinburger** [comment]
there is a "codecov/patch" and a "codecov/project" under "some checks were not successful" (I was incorrect in saying report, I meant check)

**Comment by heinburger** [comment]
ok - i see - looks like we set specific targets for the individual pull request? also we are seeing the entire project diff? Should we have both?

**Comment by menor** [comment]
I don't know if we should have both, your call

**Pull request merged**
